services:
  cassandra:
    image: cassandra:4.1
    container_name: cassandra-db
    ports:
      - "9042:9042"
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 10s
      retries: 10
    volumes:
      - ./src/main/resources/schema.cql:/docker-entrypoint-initdb.d/schema.cql

  app:
    build: .
    depends_on:
      cassandra:
        condition: service_healthy
    ports:
      - "8081:8081"


